spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disorder
    useUnicode: true
    characterEncoding: UTF-8
    serverTimezone: GMT+8
    username: root
    password: MySQLp@ssword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.e9e95d76dd77f777
            clientSecret: 01d64f6c1fb1466f69c545dc37084ee237c79c7f
          google:
            clientId: 330674424419-2rqrusbm48n09t25cvcr8o864unqd2a5.apps.googleusercontent.com
            clientSecret: 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
    jwt:
      secret-key: 556A576E5A7234753778214125442A472D4B6150645367566B59703273357638
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  mail:
    host: smtp.gmail.com
    smtp:
      port: 587
    username: cga106g3lycoris@gmail.com
    password: ktpwveowbubgisxa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true